functional:
- Пользователь должен иметь возможность искать товары по ключевому слову или категории
- Пользователь должен иметь возможность фильтровать товары
- Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
- Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
- Пользователь должен иметь возможность добавлять товары в корзину и продолжать выбирать товары в каталоге
- Пользователь должен иметь возможность видеть на странице товара название, рейтинг, цена со скидкой и без.
- Пользователь должен иметь возможность видеть в каталоге товара название, рейтинг, цена со скидкой и без.
- Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты.
- Пользователь должен иметь возможность удалить товар из корзины и продолжить выбирать товар из каталога.
non-functional:
- Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
- Сайт должен быть безопасным и защищать данные пользователя
- Сайт должен иметь мобильную версию
- Сайт нужно протестировать на совместимость с последними версиями браузеров
- Важно, чтобы сайт мог обрабатывать большое количество трафика
- Сайт должен быть доступен на различных устройствах
- Коорзина будет хранится в сессии браузера
implicit:
- Удаление товара должно быть с подтверждением
- Пользователь должен иметь возможность искать товар по ценновому диапозону
- Возможность оформить заказ с переходом на страницу оплаты
